package report

import (
	"strings"
	"testing"
	"time"

	"github.com/rswestmoreland/dbreport/internal/config"
	dbreportdb "github.com/rswestmoreland/dbreport/internal/db"
)

func TestRenderHTMLIncludesCoreSections(t *testing.T) {
	cfg := config.Config{Title: "Test Report"}
	results := []dbreportdb.Result{
		{
			Query:    config.QueryConfig{ID: "total", Title: "Total", Type: "metric"},
			Columns:  []string{"value"},
			Rows:     [][]dbreportdb.Cell{{dbreportdb.ConvertCell(int64(42))}},
			Duration: time.Millisecond,
		},
		{
			Query:    config.QueryConfig{ID: "rows", Title: "Rows", Type: "table"},
			Columns:  []string{"name", "count"},
			Rows:     [][]dbreportdb.Cell{{dbreportdb.ConvertCell("alpha"), dbreportdb.ConvertCell(int64(7))}},
			Duration: time.Millisecond,
		},
	}

	doc, err := NewDocument(cfg, results)
	if err != nil {
		t.Fatalf("NewDocument failed: %v", err)
	}

	rendered, err := RenderHTML(doc)
	if err != nil {
		t.Fatalf("RenderHTML failed: %v", err)
	}
	text := string(rendered)

	for _, want := range []string{"Test Report", "Total", "Rows", "alpha", "Generated by dbreport"} {
		if !strings.Contains(text, want) {
			t.Fatalf("rendered HTML missing %q", want)
		}
	}
}

func TestRenderBarChart(t *testing.T) {
	cfg := config.Config{Title: "Chart Report"}
	results := []dbreportdb.Result{
		{
			Query:    config.QueryConfig{ID: "status", Title: "Status", Type: "bar", LabelColumn: "status", ValueColumn: "count"},
			Columns:  []string{"status", "count"},
			Rows:     [][]dbreportdb.Cell{{dbreportdb.ConvertCell("open"), dbreportdb.ConvertCell(int64(3))}},
			Duration: time.Millisecond,
		},
	}

	doc, err := NewDocument(cfg, results)
	if err != nil {
		t.Fatalf("NewDocument failed: %v", err)
	}
	rendered, err := RenderHTML(doc)
	if err != nil {
		t.Fatalf("RenderHTML failed: %v", err)
	}

	text := string(rendered)
	if !strings.Contains(text, "chart-bar") {
		t.Fatalf("expected bar chart markup")
	}
	if !strings.Contains(text, "<table>") {
		t.Fatalf("expected fallback table by default")
	}
}

func TestRenderChartWithoutFallbackTable(t *testing.T) {
	showTable := false
	cfg := config.Config{Title: "Chart Report"}
	results := []dbreportdb.Result{{
		Query:    config.QueryConfig{ID: "daily", Title: "Daily", Type: "line", LabelColumn: "day", ValueColumn: "count", ShowTable: &showTable},
		Columns:  []string{"day", "count"},
		Rows:     [][]dbreportdb.Cell{{dbreportdb.ConvertCell("2026-05-24"), dbreportdb.ConvertCell(int64(3))}},
		Duration: time.Millisecond,
	}}
	doc, err := NewDocument(cfg, results)
	if err != nil {
		t.Fatalf("NewDocument failed: %v", err)
	}
	rendered, err := RenderHTML(doc)
	if err != nil {
		t.Fatalf("RenderHTML failed: %v", err)
	}
	if strings.Contains(string(rendered), "<table>") {
		t.Fatalf("expected fallback table to be suppressed")
	}
}
